config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/show'
  get 'recommendations/new'

  resources :polls do
    resources :votes, only: %i[show new create]
    resources :choices
    resources :recommendations, only: %i[show new create]
    member do
      get "settings"
      get "private"
      get "success"
    end
    collection do
      get "search"
      get "lookup"
    end
  end
  resources :votes, only: %i[show new create]
  resources :claimants, only: %i[show new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/choice.rb
# == Schema Information
#
# Table name: choices
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string           not null
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  poll_id    :bigint           not null
#
# Indexes
#
#  index_choices_on_poll_id  (poll_id)
#
# Foreign Keys
#
#  fk_rails_...  (poll_id => polls.id)
#
class Choice < ApplicationRecord
  belongs_to :poll, inverse_of: :choices
  has_many :votes
  
  validates :title, presence: true
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_poll
  before_action :set_choice, only: %i[show edit update destroy]

  def show
  end

  def new
    @choice = @poll.choices.new
  end

  def create
    @choice = @poll.choices.create(choice_params)

    respond_to do |format|
      if @choice.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.append("choices", partial: "choices/choice", locals: {choice: @choice})
        end
        format.html { redirect_to private_poll_path(@poll) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to private_poll_path(@poll) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @choice.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@choice) }
      format.html { redirect_to poll_path(@poll) }
    end
  end

  private

  def set_choice
    @choice = Choice.find(params[:id])
  end

  def set_poll
    @poll = Poll.friendly.find(params[:poll_id])
  end

  def choice_params
    params.require(:choice).permit(:title, :url, :content)
  end
end

app/views/choices/_choice.html.erb
<%= turbo_frame_tag dom_id(choice) do %>
  <%= content_tag :h3, choice.title %>
  <%= content_tag :div, class: "choice-url" do %>
    URL: <%= link_to choice.url, choice.url %>
  <% end unless choice.url.blank? %>
  <%= content_tag :p, class: "choice-content" do %>
    <%= choice.content %>
  <% end unless choice.content.blank? %>
  <%= link_to "edit", edit_poll_choice_path(choice.poll, choice) %>
  <%= link_to "delete", poll_choice_path(choice.poll, choice), method: :delete, data: { confirm: "Are you sure you want to delete this choice?" } %>
<% end %>

app/views/choices/_choice_form.html.erb
<%= content_tag :div, class: "nested-form-wrapper", data: { "new-record": f.object.new_record? } do %>
  <fieldset>
    <legend>Choice</legend>
    <%= f.hidden_field :_destroy %>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :url, "URL" %><br>
    <%= f.text_field :url %>
    <br>
    <%= f.label :content, "Details" %><br>
    <%= f.text_area :content %>  
    <br>
    <%= button_tag "Delete", type: "button", data: { action: "nested-form#remove" } %>
  </fieldset>

<% end %>

app/views/choices/_form.html.erb
<%= form_with(model: [@poll, @choice], id: "choice_form", data: { controller: "form", action: "turbo:submit-end->form#reset"}) do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :url, "URL" %>
  <%= f.text_field :url %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit @choice.new_record? ? "Create choice" : "Update choice", data: { "form-target": "submitbtn" } %>
<% end %>

app/views/choices/edit.html.erb
<h1>Edit Choice</h1>
<turbo-frame id="<%= dom_id(@choice) %>">
  <%= render 'form' %>
</turbo-frame>

app/views/choices/new.html.erb
<h1>New Choice</h1>
<turbo-frame id="new_choice">
  <%= render 'form' %>
</turbo-frame>

app/views/choices/show.html.erb
<%= render @choice %>