config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/show'
  get 'recommendations/new'

  resources :polls do
    resources :votes, only: %i[show new create]
    resources :choices
    resources :recommendations, only: %i[show new create]
    member do
      get "settings"
      get "private"
      get "success"
    end
    collection do
      get "search"
      get "lookup"
    end
  end
  resources :votes, only: %i[show new create]
  resources :claimants, only: %i[show new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/poll.rb
# == Schema Information
#
# Table name: polls
#
#  id                    :bigint           not null, primary key
#  access_token          :string           not null
#  allow_comments        :boolean          default(FALSE), not null
#  allow_recommendations :boolean          default(FALSE), not null
#  allow_sharing         :boolean          default(FALSE), not null
#  claimed_at            :datetime
#  discoverable          :boolean          default(FALSE), not null
#  published             :boolean          default(TRUE), not null
#  slug                  :string           not null
#  title                 :string           not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  claimant_id           :bigint
#
# Indexes
#
#  index_polls_on_claimant_id  (claimant_id)
#  index_polls_on_slug         (slug)
#
# Foreign Keys
#
#  fk_rails_...  (claimant_id => claimants.id)
#
class Poll < ApplicationRecord
  ## 0. MODEL EXTENSIONS
  # - includes / extends
  extend FriendlyId

  # - Gems
  friendly_id :slug

  # - serialized attributes
  ## 1. ASSOCIATIONS /ATTRIBUTES
  belongs_to :claimant, optional: true
  has_many :choices, dependent: :destroy, inverse_of: :poll
  has_many :recommendations, dependent: :destroy
  has_many :votes, through: :choices

  accepts_nested_attributes_for :choices, allow_destroy: true

  has_rich_text :content

  # - attr_accessible

  ## 2. SCOPES
  scope :claimed, -> { where("claimed_at IS NOT NULL") }
  scope :unclaimed, -> { where("claimed_at IS NULL") }

  ## 3. CLASS METHODS

  ## 4. VALIDATES
  validates :title, presence: true
  validates :choices, length: {minimum: 2, message: "are required. Please include at least 2 choices."}

  ## 5. CALLBACKS
  before_create :setup_poll
  after_save :claimant_check

  ## 6. INSTANCE METHODS
  # - first attribues formatting
  # - other methods
  def setup_poll
    update_slug
    update_access_token
  end

  def update_slug
    slug = generate_slug
    self.slug = slug
  end

  def generate_slug
    loop do
      value = [*("a".."z"), *("0".."9")].sample(8).join
      break value unless self.class.exists?(slug: value)
    end
  end

  def update_access_token
    access_token = generate_access_token
    self.access_token = access_token
  end

  def generate_access_token
    (Faker::Color.color_name + Faker::Ancient.god + Faker::Military.army_rank).delete(" ")
  end

  def claimant_check
    return unless previous_changes["claimant_id"].present?

    touch(:claimed_at) if claimant_id.present?

    update_column(:claimed_at, nil)
  end
  # - private methods
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i[show settings private update success]

  def index
    @polls = Poll.all
  end

  def show
  end

  def new
    @poll = Poll.new
    2.times { @poll.choices.build }
  end

  def create
    @poll = Poll.create(poll_params)

    if @poll.save
      redirect_to success_poll_path(@poll), success: "Poll created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if !params[:access_token].present?
      redirect_to lookup_polls_path
    else
      @poll = Poll.friendly.find(params[:id])

      if @poll.access_token != params[:access_token]
        redirect_to lookup_polls_path
      end
    end
  end

  def update
    if @poll.update(poll_params)
      redirect_to poll_path(@poll)
    else
      render :edit
    end
  end

  def settings
  end

  def search
  end

  def lookup
  end

  def private
  end

  def success
  end

  private

  def set_poll
    @poll = Poll.includes(:choices).friendly.find(params[:id])
  end

  def poll_params
    params.require(:poll).permit(:title, :content, :allow_comments, :allow_recommendations, :allow_sharing, :discoverable, :published, choices_attributes: [:title, :url, :content, :_destroy])
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/index.html.erb
<h1>Polls#index</h1>
<p>Find me in app/views/polls/index.html.erb</p>
<ul>
<% @polls.each do |poll| %>
  <li><%= link_to poll.slug, poll_path(poll.slug) %></li>
<% end %>
</ul>
<%= link_to "create", new_poll_path %>

app/views/polls/lookup.html.erb
<h1>Look up your Poll</h1>
<%= label_tag :access_token %>
<%= text_field_tag :access_token %>
<%= button_tag "Look Up Poll" %>

app/views/polls/new.html.erb
<h1>Create Poll</h1>
<%= form_with(model: @poll, data: { controller: "nested-form"}, html: { autocomplete: :off }) do |f| %>
  <% if @poll.errors.any? %>
    <p>The following issues prevented the poll from being saved:</p>
    <ul>
      <% @poll.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <template data-nested-form-target="template">
    <%= f.fields_for :choices, Choice.new, child_index: "NEW_RECORD" do |choice_fields| %>
      <%= render partial: "choices/choice_form", locals: { f: choice_fields } %>
    <% end %>
  </template>
  <fieldset>
    <legend>Poll Details</legend>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title, placeholder: "What kind of car should I buy?", autofocus: true %>
    <br>
    <%= f.label :content %><br>
    <%= f.rich_text_area :content %>  
  </fieldset>
  <br>
  <div class="nested-form-fields">
    <%= f.fields_for :choices do |ff| %>
      <%= render partial: "choices/choice_form", locals: { f: ff } %>
    <% end %>
    <div data-nested-form-target="target"></div>
  </div>
  <br>
  <button data-action="nested-form#add">Add</button>
  <%= f.submit %>
<% end %>

app/views/polls/private.html.erb
<h1>Poll: <%= @poll.title %></h1>
<h2>Details</h2>
<p>
<%= @poll.content %>
</p>
<h2>Choices</h2>
<ul id="choices" data-controller="">
  <%= render @poll.choices %>
</ul>
<details>
  <summary>
    <%= button_tag "Add Choice" %>
  </summary>
  <%= turbo_frame_tag "new_choice", src: new_poll_choice_path(@poll), target: "_top" %>
</details>

<h2>Settings</h2>
<%= render(CheckboxFormComponent.new(object: @poll, field: :allow_comments, label: "Allow Comments")) %>
<%= render(CheckboxFormComponent.new(object: @poll, field: :allow_recommendations, label: "Allow Recommendations")) %>
<%= render(CheckboxFormComponent.new(object: @poll, field: :allow_sharing, label: "Allow Sharing")) %>
<%= render(CheckboxFormComponent.new(object: @poll, field: :discoverable, label: "Discoverable")) %>
<%= render(CheckboxFormComponent.new(object: @poll, field: :published, label: "Published")) %>

<%= render(ShareCardComponent.new(poll: @poll, title: "Share your Poll!", subtitle: "Anyone with this link will be able to vote on your poll.", button_text: "Copy to Clipboard")) %>

app/views/polls/search.html.erb
<h1>Search for a Poll</h1>

app/views/polls/settings.html.erb
<%= @poll.slug %>

app/views/polls/show.html.erb
<%= link_to "back", polls_path %>
<%= content_tag :article do %>
  <h1><%= @poll.title %></h1>
  <%= content_tag :p, @poll.content %>
<% end %>
<%= content_tag :aside do %>
  <%= content_tag :section do %>
    <h2>Cast a Vote</h2>
    <%= turbo_frame_tag "new_vote", src: new_poll_vote_path(@poll), target: "_top" %>
  <% end %>
  <%= content_tag :section do %>
    <h2>Make a Recommenation</h2>
    <%= turbo_frame_tag :new_recommendation, src: new_poll_recommendation_path(@poll), target: "_top"  %>
  <% end if @poll.allow_recommendations %>
<% end %>

app/views/polls/success.html.erb
<%= content_tag :h1, "Poll Successfully created!" %>

<%= content_tag :article do %>
  <%= content_tag :h2, @poll.title %>
  <%= content_tag :p, @poll.content %>
  Choices: <%= @poll.choices.count %>
<% end %>

<% if @poll.claimant_id.present? %>
  <%= turbo_frame_tag dom_id(@poll.claimant), src: claimant_path(@poll.claimant) %>
<% else %>  
  <%= turbo_frame_tag "new_claimant", src: new_claimant_path(poll: @poll), target: "_top" %>
<% end %>
<%= render(ShareCardComponent.new(poll: @poll, title: "Share your Poll!", subtitle: "Anyone with this link will be able to vote on your poll.", button_text: "Copy to Clipboard")) %>